apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kanban-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: kanban.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kanban-ui-service
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: kanban-app
            port:
              number: 8080
  - host: adminer.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: adminer-service
            port:
              number: 8080